name: Bug report
description: File a bug report
title: 'fix: <short summary>'
labels: ['priority-high']
body:
  - type: input
    id: env
    attributes:
      label: Environment
      description: Branch/commit, Go version, OS, Database version
      placeholder: e.g., main/abc1234, Go 1.21.5, Ubuntu 22.04, MySQL 8.0.35
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Exact steps to reproduce the bug
      placeholder: |
        1. 启动应用 `make dev`
        2. 发送请求 `curl -X POST http://localhost:8080/api/drinks`
        3. 观察响应结果
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen?
      placeholder: e.g., 应该返回201状态码和新创建的饮品数据
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior & logs
      description: What actually happened? Include error logs, stack traces
      placeholder: |
        实际结果: 返回500错误
        
        错误日志:
        ```
        2024/01/01 10:00:00 Error creating drink: database connection failed
        ```
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context about the problem
      placeholder: e.g., 只在生产环境发生，本地开发正常